### PR TITLE
Feature/allow unmapped reads downsampling

### PR DESCRIPTION
**Pull request by jsnedecor**

### CODE REVIEW

**Comment by quejebo** [comment]
@wukevin Want to review this? :D

**Comment by jsnedecor** [comment]
Seems like Kevin's not available, so is it okay to merge this in?

**Comment by wukevin** [comment]
Sorry just saw this in my flood of other Github notifications from good ol grad school. Lemme take a look.

**Comment by wukevin** [comment]
Does this approach actually work? My memory is that pysam doesn't allow for you to fetch the reads that are unmapped: https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.fetch

Doesn't this break the multithreaded part of the logic?

**Comment by jsnedecor** [comment]
Right, but if you don't use fetch specifically, it'll keep the unmapped reads. How does it break the multithreading? It just uses chromosome "*" as an extra chromosome (i.e, anything unmapped) and keeps it in its own thread.

**Comment by wukevin** [comment]
Oh I didn't realize you could give it "*" as a "chromosome" to fetch the unmapped reads. Cool, looks good to me then.

**Pull request merged**
